
sonar.projectKey=devblog
sonar.projectName=devblog
# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources= devblog/routes, devblog/models, devblog/middleware, devblog/controllers, devblog/utils, devblog/app.js