# Goal - I have to do SAST for my Code

name: Code Quality

on:
  workflow_call:

jobs:
  sast:
    name: CodeQL SAST Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v4