#Goal - To ensure my running application is free from OWASP top 10 security vulnerabilities and issues.

name: OWASP ZAP DAST Scan

on:
  workflow_call:

jobs:
  dast:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for application
        run: |
          timeout 180s sh -c 'until curl -s http://${{ secrets.EC2_HOST }}:3000 > /dev/null; do echo "waiting for app..."; sleep 5; done'

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://${{ secrets.EC2_HOST }}:3000'
          fail_action: false
          allow_issue_write: false
          cmd_options: '-a'

