# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
  push:
    branches: [main]

jobs:

    ## -----CI -----
    # Code stage
    code-quality:
        uses: ./.github/workflows/code-quality.yml