# Goal - To Run End to End DevSecOps CI Pipeline

# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml
  
  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml
  
  docker-scans:
    uses: ./.github/workflows/docker-scans.yml
    secrets: inherit

  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit
  
  docker-push:
    needs: [code-quality, secret-scanning, dependency-scan, docker-scans, sonar-scan]
    uses: ./.github/workflows/docker-push.yml
    secrets: inherit

  
  
